import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";
import { io, Socket } from "socket.io-client";
import { useRouter } from "next/router";
import { User } from "../types";
import socketEvents from "constants/events";

let socket: Socket;

const Home: NextPage = () => {
  const [messages, setMessages] = useState<string[]>([]);
  const [selectedCard, setSelectedCard] = useState<number | null>(null);
  const [users, setUsers] = useState<User[]>([]);
  const [showCards, setShowCards] = useState(false);

  const router = useRouter();

  useEffect(() => {
    const socketInitializer = async () => {
      await fetch("/api/socket");
      socket = io();

      if (!socket || !router.query.name || !router.query.room) return;

      console.log("joining");
      socket.emit("join", { name: router.query.name, room: router.query.room });

      socket.on(socketEvents.updateCard, (users: User[]) => {
        console.log(users);
        setUsers(users);
      });
      socket.on(socketEvents.setMessage, ({ message }) => {
        // Quick display of user joined
        setMessages((messages) => [...messages, message]);
      });
      socket.on(socketEvents.addUser, (user) => {
        setUsers((users) => [...users, user]);
      });

      socket.on(socketEvents.setUsers, (users) => {
        setUsers(users);
      });

      socket.on(socketEvents.showCards, () => {
        setShowCards(true);
      });

      socket.on(socketEvents.deleteEstimations, (users: User[]) => {
        setShowCards(false);
        setUsers(users);
        setSelectedCard(null);
      });
    };

    socketInitializer();
  }, [router.query]);

  console.log("actual users in FE:", users);

  const selectCardHandler = (e: number) => {
    setSelectedCard(e);
    socket.emit(socketEvents.updateCard, e);
  };

  const handleShowCards = () => {
    socket.emit(socketEvents.showCards);
  };

  const handleDeleteEstimations = () => {
    socket.emit(socketEvents.deleteEstimations);
    setSelectedCard(null);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          {messages.map((val, i) => {
            return <div key={i}>{val}</div>;
          })}
        </div>
        <div className={styles.grid}>
          <div
            className={styles.card}
            onClick={() => selectCardHandler(1)}
            style={selectedCard === 1 ? { border: "2px solid blue" } : {}}
          >
            1
          </div>
          <div
            className={styles.card}
            onClick={() => selectCardHandler(2)}
            style={selectedCard === 2 ? { border: "2px solid blue" } : {}}
          >
            2
          </div>
        </div>
        <div>
          {users.length > 0 &&
            users.map((user: User) => (
              <div key={user.name}>
                <span>{user.name}</span>
                <span>{user.selectedCard}</span>
              </div>
            ))}
        </div>
        <button onClick={handleShowCards}>Show cards</button>
        <button onClick={handleDeleteEstimations}>Delete estimations</button>
      </main>
    </div>
  );
};

export default Home;
